spring:
  sql.init.mode: always
  output.ansi.enabled: ALWAYS

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: true
      default_schema: public

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/shareit
    username: dbuser
    password: 12345

logging.level:
  org.springframework:
    orm.jpa: INFO
    transaction: INFO
    transaction.interceptor: INFO
    orm.jpa.JpaTransactionManager: INFO
  org.zalando.logbook: TRACE
  ru.practicum.shareit: INFO