spring:
  sql.init.mode: always
  output.ansi.enabled: ALWAYS

  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/shareit
    username: dbuser
    password: 12345

logging.level:
  org.springframework:
    orm.jpa: INFO
    transaction: INFO
    transaction.interceptor: INFO
    orm.jpa.JpaTransactionManager: DEBUG
  org.zalando.logbook: TRACE
